// build.cjs — takes the per-language file icons out of material-icon-theme and
// writes them as ONE vendored JS module.
//
// ROLE IN THE SYSTEM. It generates public/app/IkonBahasa.ts, which the file tree
// reads. Run it by hand:
//
//     npm install --no-save material-icon-theme && node scripts/ikon-bahasa/build.cjs
//
// WHY VENDORED AND NOT A DEPENDENCY. The app loads its own assets with no CDN
// and no bundler at run time, and the original package carries 1250 SVGs
// (1.6 MB) while only dozens ever appear in a file tree. A runtime dependency
// would mean carrying all of it for a fraction.
//
// WHY ONE MODULE AND NOT 30 SVG FILES. Separate files mean one HTTP request per
// icon the first time the tree renders. Inlined, they arrive inside a module
// that is loaded anyway.
//
// Source: material-icon-theme (MIT) — the same icon theme VS Code uses, so the
// icons are the ones people already recognise rather than imitations.
"use strict";

const fs = require("fs");
const path = require("path");

const AKAR = path.resolve(__dirname, "..", "..");
const SUMBER = path.join(AKAR, "node_modules", "material-icon-theme", "icons");
// .ts, not .jsx: this table contains no JSX, and emitting .jsx would undo
// the migration on the next regeneration.
const TUJUAN = path.join(AKAR, "public", "app", "IkonBahasa.ts");

// Extension -> icon file name. Several extensions share one icon (mjs and cjs
// are both javascript), and that is correct: what is being distinguished is the
// language, not
// akhiran berkasnya.
const PETA = {
  js: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  jsx: "react",
  ts: "typescript",
  tsx: "react_ts",
  py: "python",
  rb: "ruby",
  go: "go",
  rs: "rust",
  java: "java",
  kt: "kotlin",
  swift: "swift",
  c: "c",
  h: "c",
  cpp: "cpp",
  cs: "csharp",
  php: "php",
  dart: "dart",
  html: "html",
  htm: "html",
  css: "css",
  scss: "sass",
  sass: "sass",
  json: "json",
  yml: "yaml",
  yaml: "yaml",
  sh: "console",
  bash: "console",
  ps1: "powershell",
  sql: "database",
  xml: "xml",
  vue: "vue",
  svelte: "svelte",
  md: "markdown",
  markdown: "markdown",
  svg: "svg",
  png: "image",
  jpg: "image",
  jpeg: "image",
  gif: "image",
  webp: "image",
};

function ambil(nama) {
  const f = path.join(SUMBER, nama + ".svg");
  if (!fs.existsSync(f)) return null;
  let svg = fs.readFileSync(f, "utf8").trim();
  // The size is stripped so the caller decides it; the viewBox is kept because
  // that is what preserves the proportions.
  svg = svg
    .replace(/\s(width|height)="[^"]*"/g, "")
    .replace(/<\?xml[^>]*\?>/g, "")
    .replace(/\s+/g, " ")
    .trim();
  return svg;
}

const isi = {};
const hilang = [];
for (const [ext, nama] of Object.entries(PETA)) {
  const svg = ambil(nama);
  if (!svg) {
    hilang.push(ext + " -> " + nama);
    continue;
  }
  isi[ext] = svg;
}

if (hilang.length) {
  console.error("Ikon tak ditemukan:\n  " + hilang.join("\n  "));
  process.exit(1);
}

const keluaran =
  `// GENERATED BY scripts/ikon-bahasa/build.cjs — DO NOT EDIT BY HAND.\n` +
  `//\n` +
  `// Per-language file icons, taken from material-icon-theme (MIT) — the same\n` +
  `// theme VS Code uses, so the icons are the ones people already recognise.\n` +
  `// Only the extensions that actually appear in the file tree are included;\n` +
  `// the original package carries 1250 SVGs and most are never used here.\n` +
  `//\n` +
  `// Regenerate: npm install --no-save material-icon-theme && node scripts/ikon-bahasa/build.cjs\n` +
  `const IKON_BAHASA: Record<string, string> = ${JSON.stringify(isi, null, 2)};\n`;

fs.writeFileSync(TUJUAN, keluaran, "utf8");
console.log(
  "  " +
    Object.keys(isi).length +
    " ekstensi -> " +
    path.relative(AKAR, TUJUAN) +
    " (" +
    Math.round(keluaran.length / 1024) +
    " KB)",
);
