// ──────────────────────────────────────────────────────────────
// Quantum A2UI Export — self-contained Flutter app
// DO NOT EDIT: This file is auto-generated by Quantum Studio.
// ──────────────────────────────────────────────────────────────
import 'package:flutter/material.dart';

// ════════════════════ A2UI RUNTIME RENDERER ════════════════════
// Minimal runtime that renders a declarative A2UI JSON spec into
// Flutter widgets — no compile needed at runtime, but compiled
// here into a standalone app for distribution.

class A2UIView extends StatefulWidget {
  final Map<String, dynamic> spec;
  const A2UIView({super.key, required this.spec});
  @override
  State<A2UIView> createState() => _A2UIViewState();
}

class _A2UIViewState extends State<A2UIView> {
  late Map<String, dynamic> _state;

  @override
  void initState() {
    super.initState();
    _state = Map<String, dynamic>.from(
        widget.spec['state'] as Map? ?? {});
  }

  @override
  void didUpdateWidget(A2UIView old) {
    super.didUpdateWidget(old);
    if (old.spec != widget.spec)
      _state = Map<String, dynamic>.from(
          widget.spec['state'] as Map? ?? {});
  }

  String _interp(String s) => s.replaceAllMapped(
      RegExp(r'\$\{(\w+)(?:\|([^}]*))?\}'),
      (m) => '${_state[m[1]] ?? m[2] ?? ''}');

  void _act(dynamic action) {
    if (action is! Map) return;
    setState(() {
      if (action['set'] != null) _state[action['set']] = action['to'];
      if (action['inc'] != null)
        _state[action['inc']] =
            ((num.tryParse('${_state[action['inc']] ?? 0}') ?? 0) +
                (action['by'] ?? 1));
      if (action['dec'] != null)
        _state[action['dec']] =
            ((num.tryParse('${_state[action['dec']] ?? 0}') ?? 0) -
                (action['by'] ?? 1));
      if (action['append'] != null)
        _state[action['append']] =
            '${_state[action['append']] ?? ''}${action['text'] ?? ''}';
      if (action['clear'] != null) _state[action['clear']] = '';
      if (action['backspace'] != null) {
        final s = '${_state[action['backspace']] ?? ''}';
        _state[action['backspace']] =
            s.isEmpty ? s : s.substring(0, s.length - 1);
      }
      if (action['eval'] != null) {
        final r = _calc('${_state[action['eval']] ?? ''}');
        _state[action['eval']] = r;
      }
    });
  }

  // Tiny safe arithmetic evaluator
  String _calc(String expr) {
    try {
      final src = expr
          .replaceAll('×', '*')
          .replaceAll('x', '*')
          .replaceAll('X', '*')
          .replaceAll('÷', '/')
          .replaceAll(':', '/')
          .replaceAll('−', '-');
      final toks = <String>[];
      final re = RegExp(r'\d*\.?\d+|[+\-*/()]');
      for (final m in re.allMatches(src)) toks.add(m[0]!);
      int pos = 0;
      late double Function() expr2, term, factor;
      expr2 = () {
        var v = term();
        while (pos < toks.length &&
            (toks[pos] == '+' || toks[pos] == '-')) {
          final op = toks[pos++];
          final r = term();
          v = op == '+' ? v + r : v - r;
        }
        return v;
      };
      term = () {
        var v = factor();
        while (pos < toks.length &&
            (toks[pos] == '*' || toks[pos] == '/')) {
          final op = toks[pos++];
          final r = factor();
          v = op == '*' ? v * r : v / r;
        }
        return v;
      };
      factor = () {
        if (pos < toks.length && toks[pos] == '(') {
          pos++;
          final v = expr2();
          if (pos < toks.length && toks[pos] == ')') pos++;
          return v;
        }
        if (pos < toks.length && toks[pos] == '-') {
          pos++;
          return -factor();
        }
        return double.tryParse(toks[pos++]) ?? 0;
      };
      final result = expr2();
      if (result == result.roundToDouble()) return result.toInt().toString();
      return result.toStringAsFixed(6).replaceFirst(RegExp(r'0+$'), '');
    } catch (_) {
      return 'Error';
    }
  }

  Color? _color(dynamic v) {
    if (v is! String) return null;
    var h = v.replaceAll('#', '');
    if (h.length == 6) h = 'FF$h';
    final n = int.tryParse(h, radix: 16);
    return n == null ? null : Color(n);
  }

  double? _d(dynamic v) =>
      v == null ? null : (v is num ? v.toDouble() : double.tryParse('$v'));

  Alignment? _align(dynamic v) {
    switch ('$v') {
      case 'top':      return Alignment.topCenter;
      case 'bottom':   return Alignment.bottomCenter;
      case 'left':     return Alignment.centerLeft;
      case 'right':    return Alignment.centerRight;
      case 'topLeft':
      case 'topleft':  return Alignment.topLeft;
      case 'topRight':
      case 'topright': return Alignment.topRight;
      case 'bottomLeft':
      case 'bottomleft': return Alignment.bottomLeft;
      case 'bottomRight':
      case 'bottomright': return Alignment.bottomRight;
      case 'center':   return Alignment.center;
    }
    return null;
  }

  Gradient? _gradient(dynamic v) {
    List? cols;
    Alignment begin = Alignment.topLeft, end = Alignment.bottomRight;
    if (v is List && v.length >= 2) {
      cols = v;
    } else if (v is Map && v['colors'] is List) {
      cols = v['colors'];
      begin = _align(v['begin']) ?? begin;
      end = _align(v['end']) ?? end;
    }
    if (cols == null) return null;
    return LinearGradient(
        begin: begin,
        end: end,
        colors: cols.map<Color>((e) => _color(e) ?? Colors.transparent).toList());
  }

  List<BoxShadow>? _shadow(dynamic v) {
    if (v == null || v == false) return null;
    if (v == true) return const [
      BoxShadow(color: Color(0x33000000), blurRadius: 12, offset: Offset(0, 4))
    ];
    if (v is Map) return [
      BoxShadow(
          color: _color(v['color']) ?? const Color(0x33000000),
          blurRadius: _d(v['blur']) ?? 12,
          spreadRadius: _d(v['spread']) ?? 0,
          offset: Offset(_d(v['dx']) ?? 0, _d(v['dy']) ?? 4))
    ];
    return null;
  }

  BoxBorder? _border(Map n) {
    final w = _d(n['borderWidth']);
    final c = _color(n['borderColor']);
    if (w == null && c == null) return null;
    return Border.all(color: c ?? const Color(0xFFE0E0E0), width: w ?? 1);
  }

  TextAlign? _textAlign(dynamic v) {
    switch ('$v') {
      case 'center':  return TextAlign.center;
      case 'right':
      case 'end':     return TextAlign.right;
      case 'left':
      case 'start':   return TextAlign.left;
      case 'justify': return TextAlign.justify;
    }
    return null;
  }

  FontWeight _weight(dynamic w, dynamic bold) {
    if (bold == true) return FontWeight.bold;
    switch ('$w') {
      case 'bold': case '700': case 'w700': return FontWeight.w700;
      case '100': case 'w100': return FontWeight.w100;
      case '200': case 'w200': return FontWeight.w200;
      case '300': case 'w300': return FontWeight.w300;
      case '400': case 'w400': case 'normal': return FontWeight.w400;
      case '500': case 'w500': return FontWeight.w500;
      case '600': case 'w600': return FontWeight.w600;
      case '800': case 'w800': return FontWeight.w800;
      case '900': case 'w900': return FontWeight.w900;
    }
    return FontWeight.normal;
  }

  List<Widget> _gap(List<Widget> ws, double? g, bool horizontal) {
    if (g == null || g <= 0 || ws.length < 2) return ws;
    final out = <Widget>[];
    for (var i = 0; i < ws.length; i++) {
      if (i > 0) out.add(
          SizedBox(width: horizontal ? g : 0, height: horizontal ? 0 : g));
      out.add(ws[i]);
    }
    return out;
  }

  IconData _icon(String name) {
    const m = {
      'add': Icons.add, 'remove': Icons.remove, 'close': Icons.close,
      'check': Icons.check, 'star': Icons.star, 'star_border': Icons.star_border,
      'home': Icons.home, 'settings': Icons.settings, 'search': Icons.search,
      'delete': Icons.delete, 'edit': Icons.edit, 'menu': Icons.menu,
      'favorite': Icons.favorite, 'favorite_border': Icons.favorite_border,
      'person': Icons.person, 'arrow_back': Icons.arrow_back,
      'arrow_forward': Icons.arrow_forward, 'play_arrow': Icons.play_arrow,
      'pause': Icons.pause, 'stop': Icons.stop, 'share': Icons.share,
      'more_vert': Icons.more_vert, 'notifications': Icons.notifications,
      'mail': Icons.mail, 'phone': Icons.phone, 'camera_alt': Icons.camera_alt,
      'shopping_cart': Icons.shopping_cart, 'lock': Icons.lock,
      'visibility': Icons.visibility, 'calendar_today': Icons.calendar_today,
      'location_on': Icons.location_on, 'wifi': Icons.wifi,
      'battery_full': Icons.battery_full, 'cloud': Icons.cloud,
      'download': Icons.download, 'refresh': Icons.refresh,
      'thumb_up': Icons.thumb_up, 'info': Icons.info, 'warning': Icons.warning,
      'chevron_right': Icons.chevron_right, 'chevron_left': Icons.chevron_left,
      'expand_more': Icons.expand_more, 'circle': Icons.circle,
    };
    return m[name] ?? Icons.circle;
  }

  List<Widget> _kids(dynamic c) =>
      (c is List) ? c.map<Widget>(_node).toList() : const [];

  bool _isBtn(String t) =>
      t == 'button' || t == 'elevatedbutton' || t == 'textbutton' || t == 'iconbutton';

  List<Widget> _rowKids(dynamic c) {
    if (c is! List) return const [];
    final allBtn = c.isNotEmpty &&
        c.every((e) => e is Map && _isBtn('${e['type'] ?? ''}'.toLowerCase()));
    if (!allBtn) return c.map<Widget>(_node).toList();
    return c.map<Widget>((e) => Expanded(
        child: Padding(padding: const EdgeInsets.all(4), child: _node(e)))).toList();
  }

  double? _cw(dynamic v) {
    final d = _d(v);
    if (d == null) return null;
    return d >= 600 ? double.infinity : d;
  }

  Widget _node(dynamic n) {
    if (n is! Map) return const SizedBox.shrink();
    final type = '${n['type'] ?? ''}'.toLowerCase();
    return _buildNode(n, type);
  }

  Widget _buildNode(Map n, String type) {
    switch (type) {
      case 'scaffold':
        return Scaffold(
          appBar: n['appbar'] == true
              ? AppBar(
                  title: Text(n['title'] ?? 'App'),
                  backgroundColor: _color(n['appBarColor']),
                  elevation: _d(n['elevation']) ?? 1)
              : null,
          backgroundColor: _color(n['background']) ?? _color(n['bg']),
          body: n['body'] != null
              ? _node(n['body'])
              : _kids(n['children']).isEmpty
                  ? null
                  : Column(children: _kids(n['children'])),
          floatingActionButton: n['fab'] != null ? _node(n['fab']) : null,
        );
      case 'column':
      case 'v':
        final kids = n['row'] == true
            ? _rowKids(n['children'])
            : _kids(n['children']);
        if (n['scroll'] == true)
          return ListView(children: _gap(kids, _d(n['gap']), false));
        final main = n['align'] != null
            ? ('${n['align']}'.contains('between')
                ? MainAxisAlignment.spaceBetween
                : '${n['align']}'.contains('around')
                    ? MainAxisAlignment.spaceAround
                    : '${n['align']}'.contains('center')
                        ? MainAxisAlignment.center
                        : '${n['align']}'.contains('end')
                            ? MainAxisAlignment.end
                            : MainAxisAlignment.start)
            : MainAxisAlignment.start;
        final cross = n['cross'] != null
            ? ('${n['cross']}'.contains('center')
                ? CrossAxisAlignment.center
                : '${n['cross']}'.contains('stretch')
                    ? CrossAxisAlignment.stretch
                    : '${n['cross']}'.contains('end')
                        ? CrossAxisAlignment.end
                        : CrossAxisAlignment.start)
            : CrossAxisAlignment.start;
        return Column(
            mainAxisAlignment: main,
            crossAxisAlignment: cross,
            children: _gap(kids, _d(n['gap']), false));
      case 'row':
      case 'h':
        final kids = n['scroll'] == true
            ? _kids(n['children'])
            : _rowKids(n['children']);
        if (n['scroll'] == true)
          return SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              child: Row(children: _gap(kids, _d(n['gap']), true)));
        return Row(children: _gap(kids, _d(n['gap']), true));
      case 'center':
        return Center(
            child: n['child'] != null ? _node(n['child']) : null);
      case 'padding':
        final p = _d(n['all']);
        final l = _d(n['left']);
        final r = _d(n['right']);
        final t = _d(n['top']);
        final b = _d(n['bottom']);
        return Padding(
            padding: p != null
                ? EdgeInsets.all(p)
                : EdgeInsets.only(
                    left: l ?? 0, right: r ?? 0, top: t ?? 0, bottom: b ?? 0),
            child: n['child'] != null ? _node(n['child']) : null);
      case 'sizedbox':
        return SizedBox(
            width: _cw(n['width']), height: _d(n['height']));
      case 'expanded':
        return Expanded(
            flex: _d(n['flex'])?.toInt() ?? 1,
            child: n['child'] != null
                ? _node(n['child'])
                : const SizedBox.shrink());
      case 'spacer':
        return Spacer(flex: _d(n['flex'])?.toInt() ?? 1);
      case 'container':
        return Container(
          width: _cw(n['width']),
          height: _d(n['height']),
          padding: n['padding'] != null
              ? EdgeInsets.all(_d(n['padding']) ?? 0)
              : null,
          margin: n['margin'] != null
              ? EdgeInsets.all(_d(n['margin']) ?? 0)
              : null,
          decoration: BoxDecoration(
            color: _color(n['color']),
            gradient: _gradient(n['gradient']),
            borderRadius: n['radius'] != null
                ? BorderRadius.circular(_d(n['radius']) ?? 0)
                : null,
            boxShadow: _shadow(n['shadow']),
            border: _border(n),
          ),
          alignment: _align(n['align']),
          child: n['child'] != null
              ? _node(n['child'])
              : _kids(n['children']).isEmpty
                  ? null
                  : Column(children: _kids(n['children'])),
        );
      case 'text':
        return Text(
          _interp('${n['text'] ?? ''}'),
          style: TextStyle(
            fontSize: _d(n['fontSize']),
            fontWeight: _weight(n['fontWeight'], n['bold']),
            color: _color(n['color']),
            fontStyle: n['italic'] == true ? FontStyle.italic : null,
            letterSpacing: _d(n['letterSpacing']),
          ),
          textAlign: _textAlign(n['align']),
        );
      case 'button':
      case 'elevatedbutton':
        return ElevatedButton(
          onPressed: n['onPress'] != null ? () => _act(n['onPress']) : null,
          style: ElevatedButton.styleFrom(
            backgroundColor: _color(n['color']),
            foregroundColor: _color(n['textColor']),
            padding: n['padding'] != null
                ? EdgeInsets.all(_d(n['padding']) ?? 0)
                : null,
            shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(_d(n['radius']) ?? 8)),
            elevation: _d(n['elevation']),
          ),
          child: n['child'] != null
              ? _node(n['child'])
              : Text(_interp('${n['text'] ?? 'Button'}')),
        );
      case 'textbutton':
        return TextButton(
          onPressed: n['onPress'] != null ? () => _act(n['onPress']) : null,
          style: TextButton.styleFrom(
            foregroundColor: _color(n['color']),
            padding: n['padding'] != null
                ? EdgeInsets.all(_d(n['padding']) ?? 0)
                : null,
          ),
          child: Text(_interp('${n['text'] ?? 'Button'}')),
        );
      case 'iconbutton':
        return IconButton(
          icon: Icon(_icon(n['icon'] ?? 'add'),
              size: _d(n['size']), color: _color(n['color'])),
          onPressed: n['onPress'] != null ? () => _act(n['onPress']) : null,
        );
      case 'icon':
        return Icon(_icon(n['icon'] ?? 'circle'),
            size: _d(n['size']), color: _color(n['color']));
      case 'image':
        return Image.network(
          '${n['url'] ?? ''}',
          width: _cw(n['width']),
          height: _d(n['height']),
          fit: BoxFit.cover,
          errorBuilder: (_, __, ___) =>
              const Icon(Icons.broken_image, size: 48),
        );
      case 'card':
        return Card(
          elevation: _d(n['elevation']) ?? 2,
          margin: n['margin'] != null
              ? EdgeInsets.all(_d(n['margin']) ?? 0)
              : null,
          child: n['child'] != null
              ? _node(n['child'])
              : _kids(n['children']).isEmpty
                  ? null
                  : Column(children: _kids(n['children'])),
        );
      case 'switch':
        return Switch(
          value: _state[n['bind']] == true,
          onChanged: n['bind'] != null
              ? (v) => setState(() => _state[n['bind']] = v)
              : null,
          activeColor: _color(n['color']),
        );
      case 'checkbox':
        return Checkbox(
          value: _state[n['bind']] == true,
          onChanged: n['bind'] != null
              ? (v) => setState(() => _state[n['bind']] = v)
              : null,
          activeColor: _color(n['color']),
        );
      case 'slider':
        return Slider(
          value: (_state[n['bind']] ?? _d(n['value']) ?? 0).toDouble(),
          min: _d(n['min']) ?? 0,
          max: _d(n['max']) ?? 100,
          divisions: _d(n['step'])?.toInt(),
          onChanged: n['bind'] != null
              ? (v) => setState(() => _state[n['bind']] = v)
              : null,
          activeColor: _color(n['color']),
        );
      case 'textfield':
        TextEditingController? ctrl;
        if (WidgetsBinding.instance.platformDispatcher.views.isNotEmpty) {
          ctrl = TextEditingController.fromValue(
              TextEditingValue(text: '${_state[n['bind']] ?? ''}'));
        }
        return TextField(
          controller: ctrl,
          obscureText: n['obscure'] == true,
          decoration: InputDecoration(
            labelText: _interp('${n['label'] ?? ''}'),
            hintText: _interp('${n['hint'] ?? ''}'),
            prefixIcon:
                n['icon'] != null ? Icon(_icon(n['icon'])) : null,
            border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(_d(n['radius']) ?? 8)),
          ),
          onChanged: n['bind'] != null
              ? (v) => setState(() => _state[n['bind']] = v)
              : null,
        );
      case 'dropdown':
      case 'select':
        final opts = n['options'] is List
            ? n['options'].map<String>((e) => '$e').toList()
            : <String>[];
        return DropdownButtonFormField<String>(
          value: _state[n['bind']] ?? (opts.isNotEmpty ? opts[0] : null),
          decoration: InputDecoration(
              labelText: _interp('${n['label'] ?? ''}')),
          items: opts
              .map((e) => DropdownMenuItem(value: e, child: Text(e)))
              .toList(),
          onChanged: n['bind'] != null
              ? (v) => setState(() => _state[n['bind']] = v)
              : null,
        );
      case 'radio':
        final opts = n['options'] is List
            ? n['options'].map<String>((e) => '$e').toList()
            : <String>[];
        return Column(
            children: opts
                .map((e) => RadioListTile<String>(
                      title: Text(e),
                      value: e,
                      groupValue: _state[n['bind']],
                      onChanged: n['bind'] != null
                          ? (v) => setState(() => _state[n['bind']] = v)
                          : null,
                    ))
                .toList());
      case 'progress':
      case 'progressbar':
        return LinearProgressIndicator(
          value: (_state[n['bind']] ?? _d(n['value']) ?? 0)
              .toDouble()
              .clamp(0, 1),
          backgroundColor: _color(n['trackColor']),
          color: _color(n['color']),
          minHeight: _d(n['height']),
        );
      case 'chip':
        return Chip(
          label: Text(_interp('${n['label'] ?? ''}')),
          avatar: n['icon'] != null
              ? Icon(_icon(n['icon']), size: 18)
              : null,
          backgroundColor: _color(n['color']),
          labelStyle: TextStyle(color: _color(n['textColor'])),
        );
      case 'wrap':
        return Wrap(
            spacing: _d(n['gap']) ?? 8,
            runSpacing: _d(n['gap']) ?? 4,
            children: _kids(n['children']));
      case 'grid':
      case 'gridview':
        return GridView.count(
          crossAxisCount: _d(n['columns'])?.toInt() ?? 2,
          childAspectRatio: _d(n['ratio']) ?? 1,
          crossAxisSpacing: _d(n['gap']) ?? 4,
          mainAxisSpacing: _d(n['gap']) ?? 4,
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          children: _kids(n['children']),
        );
      case 'listview':
      case 'list':
        return ListView(
            shrinkWrap: true,
            physics: const NeverScrollableScrollPhysics(),
            children: _kids(n['children']));
      case 'divider':
        return Divider(
            color: _color(n['color']),
            height: _d(n['height']),
            thickness: _d(n['thickness']));
      default:
        final kids = _kids(n['children']);
        return kids.isEmpty
            ? const SizedBox.shrink()
            : Column(children: kids);
    }
  }

  @override
  Widget build(BuildContext context) {
    final root = widget.spec['root'] ?? widget.spec;
    return root is Map ? _node(root) : const Center(child: Text('Invalid spec'));
  }
}

// ════════════════════ APP ENTRY ════════════════════
// The entry point (main + _spec) is generated by the server endpoint.
// Placeholder — replace with generated content:
// void main() { runApp(MaterialApp(..., home: A2UIView(spec: json.decode(_rawSpec)))); }
