name: quantum_studio
description: Quantum Web Dev studio (embedded Flutter module)
publish_to: none
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
